import { describe, expect, it } from "vitest";
import {
  normalizeApprovalLevel,
  normalizeOperationParams,
  normalizeProposalString,
  normalizeProposeTaskArgs,
} from "./propose-task-args.js";

describe("normalizeProposalString", () => {
  it("strips Gemma-style wrappers and quotes", () => {
    expect(normalizeProposalString('<|"|>L2<|"|>')).toBe("L2");
    expect(normalizeProposalString('"actuator:pump:P1"')).toBe("actuator:pump:P1");
  });
});

describe("normalizeApprovalLevel", () => {
  it("accepts wrapped approval levels", () => {
    expect(normalizeApprovalLevel('<|"|>L2<|"|>')).toBe("L2");
  });

  it("defaults invalid approval levels to L2", () => {
    expect(normalizeApprovalLevel("bad")).toBe("L2");
    expect(normalizeApprovalLevel(undefined)).toBe("L2");
  });
});

describe("normalizeOperationParams", () => {
  it("passes through object params", () => {
    expect(normalizeOperationParams({ zone: "zone-1" })).toEqual({ zone: "zone-1" });
  });

  it("parses loose object strings", () => {
    expect(normalizeOperationParams('{zone:<|"|>zone-1<|"|>,duration:10,enabled:true}')).toEqual({
      zone: "zone-1",
      duration: 10,
      enabled: true,
    });
  });

  it("parses JSON object strings", () => {
    expect(normalizeOperationParams('{"zone":"zone-1"}')).toEqual({ zone: "zone-1" });
  });
});

describe("normalizeProposeTaskArgs", () => {
  it("fills safe defaults for missing summary and reasoning", () => {
    expect(normalizeProposeTaskArgs({
      targetRef: '"actuator:pump:P1"',
      operation: '"start"',
      approvalLevel: '<|"|>L2<|"|>',
      operationParams: '{zone:<|"|>zone-1<|"|>}',
    })).toEqual({
      summary: "Proposed start on actuator:pump:P1",
      reasoning: "Generated by the planner from current mesh context. Review sensor evidence before approval.",
      targetRef: "actuator:pump:P1",
      operation: "start",
      approvalLevel: "L2",
      operationParams: { zone: "zone-1" },
    });
  });

  it("returns null when targetRef or operation is unusable", () => {
    expect(normalizeProposeTaskArgs({ operation: "start" })).toBeNull();
    expect(normalizeProposeTaskArgs({ targetRef: "actuator:pump:P1" })).toBeNull();
  });
});
