import type { ApprovalLevel } from "../types.js";

const DEFAULT_PROPOSAL_REASONING = "Generated by the planner from current mesh context. Review sensor evidence before approval.";

export type NormalizedProposeTaskArgs = {
  summary: string;
  reasoning: string;
  targetRef: string;
  operation: string;
  operationParams?: Record<string, unknown>;
  approvalLevel: ApprovalLevel;
};

export function normalizeProposalString(value: unknown): string {
  if (typeof value !== "string") return "";
  return value
    .replace(/<\|[^|]*\|>/g, "")
    .replace(/^[\s'"`]+|[\s'"`]+$/g, "")
    .trim();
}

export function normalizeApprovalLevel(rawApprovalLevel: unknown): ApprovalLevel {
  const normalized = normalizeProposalString(rawApprovalLevel).toUpperCase();
  if (normalized === "L1" || normalized === "L2" || normalized === "L3") {
    return normalized;
  }
  return "L2";
}

export function normalizeOperationParams(rawOperationParams: unknown): Record<string, unknown> | undefined {
  if (!rawOperationParams) return undefined;
  if (typeof rawOperationParams === "object" && !Array.isArray(rawOperationParams)) {
    return rawOperationParams as Record<string, unknown>;
  }
  if (typeof rawOperationParams !== "string") return undefined;

  const normalized = normalizeProposalString(rawOperationParams);
  if (!normalized) return undefined;

  try {
    const parsed = JSON.parse(normalized);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
  } catch {
    // Fall through to loose object parsing
  }

  const body = normalized.replace(/^\{/, "").replace(/\}$/, "").trim();
  if (!body) return undefined;

  const entries = body
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const splitIndex = part.indexOf(":");
      if (splitIndex === -1) return null;
      const key = normalizeProposalString(part.slice(0, splitIndex));
      const rawValue = normalizeProposalString(part.slice(splitIndex + 1));
      if (!key) return null;
      return [key, parseLooseValue(rawValue)] as const;
    })
    .filter((entry): entry is readonly [string, unknown] => entry !== null);

  return entries.length > 0 ? Object.fromEntries(entries) : undefined;
}

export function normalizeProposeTaskArgs(args: Record<string, unknown>): NormalizedProposeTaskArgs | null {
  const targetRef = normalizeProposalString(args.targetRef);
  const operation = normalizeProposalString(args.operation);
  if (!targetRef || !operation) return null;

  const summary = normalizeProposalString(args.summary) || `Proposed ${operation} on ${targetRef}`;
  const reasoning = normalizeProposalString(args.reasoning) || DEFAULT_PROPOSAL_REASONING;

  return {
    summary,
    reasoning,
    targetRef,
    operation,
    operationParams: normalizeOperationParams(args.operationParams),
    approvalLevel: normalizeApprovalLevel(args.approvalLevel),
  };
}

function parseLooseValue(value: string): unknown {
  if (!value) return "";
  if (/^-?\d+(\.\d+)?$/.test(value)) return Number(value);
  if (/^(true|false)$/i.test(value)) return value.toLowerCase() === "true";
  return value;
}
